# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubygems-proxy_server}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jrun"]
  s.date = %q{2009-12-04}
  s.description = %q{A gem source proxy}
  s.email = %q{jeremy.burks@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/proxy_app.rb",
     "lib/proxy_server_command.rb",
     "lib/rubygems_plugin.rb",
     "rubygems-proxy_server.gemspec",
     "spec/mockgemui.rb",
     "spec/proxy_app_spec.rb",
     "spec/proxy_server_command_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jrun/rubygems-proxy_server}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A gem source proxy.}
  s.test_files = [
    "spec/mockgemui.rb",
     "spec/proxy_app_spec.rb",
     "spec/proxy_server_command_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, ["~> 1.0.1"])
      s.add_runtime_dependency(%q<sinatra>, ["~> 0.9.4"])
      s.add_development_dependency(%q<rspec>, ["~> 1.2.9"])
      s.add_development_dependency(%q<rack-test>, ["~> 0.5.2"])
      s.add_development_dependency(%q<sham_rack>, ["~> 1.1.2"])
      s.add_development_dependency(%q<grancher>, ["> 0"])
    else
      s.add_dependency(%q<rack>, ["~> 1.0.1"])
      s.add_dependency(%q<sinatra>, ["~> 0.9.4"])
      s.add_dependency(%q<rspec>, ["~> 1.2.9"])
      s.add_dependency(%q<rack-test>, ["~> 0.5.2"])
      s.add_dependency(%q<sham_rack>, ["~> 1.1.2"])
      s.add_dependency(%q<grancher>, ["> 0"])
    end
  else
    s.add_dependency(%q<rack>, ["~> 1.0.1"])
    s.add_dependency(%q<sinatra>, ["~> 0.9.4"])
    s.add_dependency(%q<rspec>, ["~> 1.2.9"])
    s.add_dependency(%q<rack-test>, ["~> 0.5.2"])
    s.add_dependency(%q<sham_rack>, ["~> 1.1.2"])
    s.add_dependency(%q<grancher>, ["> 0"])
  end
end

